FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ARG NEXT_PUBLIC_API_URL=http://127.0.0.1:8000
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_EMAIL_VERIFICATION_ENABLED=true
ENV NEXT_PUBLIC_EMAIL_VERIFICATION_ENABLED=$NEXT_PUBLIC_EMAIL_VERIFICATION_ENABLED
ARG NEXT_PUBLIC_DEV_OPERATOR_BUTTON_ENABLED=false
ENV NEXT_PUBLIC_DEV_OPERATOR_BUTTON_ENABLED=$NEXT_PUBLIC_DEV_OPERATOR_BUTTON_ENABLED
ARG NEXT_PUBLIC_DEV_OPERATOR_USERNAME=
ENV NEXT_PUBLIC_DEV_OPERATOR_USERNAME=$NEXT_PUBLIC_DEV_OPERATOR_USERNAME
ARG NEXT_PUBLIC_DEV_OPERATOR_PASSWORD=
ENV NEXT_PUBLIC_DEV_OPERATOR_PASSWORD=$NEXT_PUBLIC_DEV_OPERATOR_PASSWORD
ARG NEXT_PUBLIC_PASSWORD_MIN_LENGTH=8
ENV NEXT_PUBLIC_PASSWORD_MIN_LENGTH=$NEXT_PUBLIC_PASSWORD_MIN_LENGTH
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/package.json ./
COPY --from=builder /app/package-lock.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.ts ./
EXPOSE 3000
CMD ["npm", "start"]
